export const DOCTORS = [
  {
    id: 'd1',
    name: 'Dr. Rajesh Verma',
    qualifications: 'MBBS, MD • General Physician',
    hospital: 'Apollo Clinic, Saket',
    fees: 300,
    startTime: '09:00',
    endTime: '14:00',
    rating: 4.9,
    reviews: 312,
    wait: '10 min wait',
    slots: 'Aaj: 3 slot baaki',
    availableMsg: 'Abhi Available',
    isAvailable: true,
    avatarBg: 'bg-brand-teal-light',
    avatarEmoji: '👨‍⚕️',
    categories: ['Sab', 'General']
  },
  {
    id: 'd2',
    name: 'Dr. Priya Sharma',
    qualifications: 'BDS, MDS • Dentist',
    hospital: 'SmileCare, Janakpuri',
    fees: 500,
    startTime: '10:00',
    endTime: '18:00',
    rating: 4.7,
    reviews: 189,
    wait: '5 min wait',
    slots: 'Aaj: 5 slot baaki',
    availableMsg: 'Abhi Available',
    isAvailable: true,
    avatarBg: 'bg-brand-blue-light',
    avatarEmoji: '👩‍⚕️',
    categories: ['Sab', 'Dentist']
  },
  {
    id: 'd3',
    name: 'Dr. Anil Kumar',
    qualifications: 'MBBS, DM • Cardiologist',
    hospital: 'Max Healthcare, Shalimar Bagh',
    fees: 800,
    startTime: '14:00',
    endTime: '20:00',
    rating: 4.8,
    reviews: 421,
    wait: 'Kal 10am se',
    slots: 'Kal: 8 slot',
    availableMsg: 'Kal available',
    isAvailable: false,
    avatarBg: 'bg-[#fcebeb]',
    avatarText: 'text-red-700',
    availBg: 'bg-red-50',
    availText: 'text-red-700',
    avatarEmoji: '🧑‍⚕️',
    categories: ['Sab', 'Cardiologist']
  },
  {
    id: 'd4',
    name: 'Dr. Sunita Rao',
    qualifications: 'MD Pediatrics • Shishu Specialist',
    hospital: 'CityMed Clinic, Dwarka',
    fees: 400,
    startTime: '08:00',
    endTime: '13:00',
    rating: 5.0,
    reviews: 98,
    wait: '15 min wait',
    slots: 'Aaj: 2 slot baaki',
    availableMsg: 'Abhi Available',
    isAvailable: true,
    avatarBg: 'bg-[#eaf3de]',
    avatarEmoji: '👩‍⚕️',
    categories: ['Sab', 'Paediatrician']
  }
];
